version: '3.8'

networks:
  dev-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: database
    ports:
      - "3306:3306"
    networks:
      dev-network:
        ipv4_address: 172.28.1.1
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=development
  java:
    build: 
      context: .
      dockerfile: Dockerfile      
    image: tomcat
    container_name: gen
    ports:
      - "8080:8080"
    networks:
      - dev-network

