version: '3.8'

services:
  java:
    build: 
      context: .
      dockerfile: Dockerfile      
    image: tomcat
    container_name: gen
    ports:
      - "8080:8080"
    volumes:
      - '.:/app'
networks:
  dev-network:
    driver: bridge
