version: '3.8'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: database
    ports:
      - "3306:3306"
    networks:
      - dev-network
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=development
      - MYSQL_USER=root
  java:
    build: 
      context: .
      dockerfile: Dockerfile      
    image: tomcat
    container_name: gen
    ports:
      - "8080:8080"
    networks:
      - dev-network
networks:
  dev-network:
    driver: bridge
